version: '3.5'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - postgres
      - rabbitmq
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - rabbitmq
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  postgres:
  rabbitmq:
